### ISSUE TITLE
Let Process1, Tee, Wye transducers receive all available inputs on await

### ISSUE THREAD

**Issue by pchiusano** [scalaz/scalaz-stream#249] opened 2014-10-01 15:22 UTC
As [mentioned here](https://github.com/scalaz/scalaz-stream/pull/237#issuecomment-55305291), I'd like to introduce the following combinators:

```Scala
def available[A]: Process1[A,Seq[A]]
def availableL[A]: Tee[A,Any,Seq[A]]
def availableR[A]: Tee[Any,A,Seq[A]]
// can have receiveAvailable, receiveAvailableL/R, etc

def await1[A]: Process1[A,A] = available[A].flatMap(emitAll)
// likewise for awaitL/R/Both
```

This will require modifying the [`Env` type](https://github.com/scalaz/scalaz-stream/blob/master/src/main/scala/scalaz/stream/Process.scala#L1058) and will be a comprehensive change. (But it should be mostly if not entirely backwards compatible, since the old combinators will still exist)

**Comment by djspiewak** [comment] 2015-04-18 00:15
@pchiusano Interesting problem with your specification.  Specifically, `await1`.  The problem is that `await1` *guarantees* that it will produce a `Process1` containing at most *one* element.  Reading that another way, it promises to *consume* at most one element from the input process.  Defining this in terms of `available` breaks that guarantee, since you will consume as many elements as are in a chunk.  There are several combinators that this breaks, but `delete` is the first one in `Process1Spec`.

I still think that `available` is a really good idea, but it has to be done as a separate algebraic case.

**Comment by djspiewak** [comment] 2015-04-18 04:21
Working on this even further, I'm not sure that this is going to work.  It breaks too much compositionality due to the consumption guarantees.  Even having *both* `await1` and `available1` in the algebra as separate cases, just having `available1` in use messes up derivative combinators.  For example, `find` is defined in terms of `filter`.  It's very clear that `filter` should be defined in terms of `available1`, but we *can't* because of `find`:

```scala
  def find[I](f: I => Boolean): Process1[I, I] =
    filter(f).once
```

The problem is that, with `filter` defined using `available1`, the transducer resulting from `find` will over-consume the source, just as I mentioned would happen with `await1`.  I really think this points to a fundamental issue with this concept, since the consumption properties of a `Process1` are not represented in the types, and thus a seemly innocuous optimization change like swapping `id` to `available1` can *silently* break downstream composition.

I'll think about ways to resolve this problem, but it's tricky.  We can't exactly "put the genie back in the bottle" after we've consumed from the input source.

**Comment by djspiewak** [comment] 2015-04-26 05:03
@pchiusano At this point, I'm very convinced that there is no way to do this without breaking compositionality inside of `Process1`.  We can't have some combinators silently over-consuming the input stream, and the way that the algebra is designed allows downstream combinators to force over-consumption if the upstream combinator uses `available` *at all*.  (this is well exemplified with `filter` and `find`)

I think that a better approach here would be to define a `liftChunks` function on `Process`.  Something like this:

```scala
def liftChunks: Process[F, Seq[O]] = suspendStep flatMap {
  case h: Halt => h
  case Step(Emit(os), cont) => Emit(os :: Nil) +: (cont extend { _.liftChunks })
  case Step(awt @ Await(_, _), cont) => (awt extend { _.liftChunks }) +: (cont extend { _.liftChunks })
}
```

This would make the chunking explicit, at which point it would be easy to write combinators like `chunkedMap`:

```scala
def chunkedMap[A, B](f: A => B): Process1[Seq[A], Seq[B]] =
  id[Seq[A]] flatMap { emit(as map f) }
```

I'd be in favor of closing this issue, as I am quite certain it is infeasible and we should concentrate on other possible solutions to the problem.

**Comment by djspiewak** [comment] 2015-05-20 18:23
I'm closing this, since there's no way to make it work with the current algebra.  Obviously, we want to make await chunking a functional part of the library, but we're doing that as part of a larger effort (#383).

**Closed by djspiewak** 2015-05-20 18:23 UTC
Labels: design/refactoring
