### ISSUE TITLE
Nested awaits run outer await's dependent finalizer twice

### ISSUE THREAD

**Issue by dansanduleac** [scalaz/scalaz-stream#353] opened 2015-03-30 14:28 UTC
According to [the 0.7 finalizers doc](https://github.com/scalaz/scalaz-stream/wiki/0.7#-finalizers), 

```scala
Process.await(t) { r => p1 onComplete f1(r) } onComplete f2
```
if this code is interrupted during `t`, then `f2` will immediately run, and `f1` will eventually run (when `t` completes), but *`f2` should not be reinvoked*.

My example is a bit more complex, with two nested awaits -- nested because one depends on the other:
```scala
import java.nio.file._
import java.util.concurrent.TimeUnit

import scalaz.concurrent.Task
import scalaz.stream.Process._
import scalaz.stream._

val path: java.nio.file.Path = Files.createTempDirectory("scalaz-stream-test")
def acq = {
    val ws = path.getFileSystem.newWatchService()
    import java.nio.file.StandardWatchEventKinds._
    path.register(ws, ENTRY_CREATE)
    ws
  }

import collection.JavaConverters._
// Wait for a WatchKey, grab all events from it and emit them, 
//   resetting afterwards (so it returns to the "ready" state), then repeat 
// this is using the same "repeat" pattern as Process.repeatEval: 
//   appending the recursive call inside the await
def repeatedStep(ws: WatchService): Process[Task, Path] =
  Process.await(Task delay ws.take()) { wk =>
    val reset = Process eval_ Task.delay{ println("resetting"); wk.reset() }
    Process emitAll wk.pollEvents().asScala.toSeq.map { 
      case w: WatchEvent[Path]@unchecked => path resolve w.context
    } onComplete reset append repeatedStep(ws)
  }
def release(ws: WatchService) = Process eval_ Task.delay {
  ws.close(); println("Releasing WatchService")
}
val newPaths = await(Task delay acq) { ws => repeatedStep(ws) onComplete release(ws) }
  .observe { io.stdOutLines.contramap((p: Path) => s"New file discovered: $p") }
  .onComplete(Process eval_ Task.delay(println("DONE")))

import scala.concurrent.duration._
implicit val s = scalaz.stream.DefaultScheduler

val dropFile =
  Process.range(0, 2) flatMap { i =>
    val f = path.resolve(s"testFile-$i")
    time.sleep(1500.milliseconds) ++ (Process eval_ Task.delay { Files.createFile(f) })
  }

(dropFile merge newPaths.wye(time.sleep(2.seconds))(wye.mergeHaltBoth)).run.run
```

What this is doing conceptually:
* `newPaths` starts watching the tmp directory, and blocks on `ws.take()` waiting for new files
* I'm interrupting `newPaths` after 2s by using `wye.mergeHaltBoth` at the bottom
* I'm creating two files at 1.5s and 3s, each of which cause the awaited `ws.take()` to return

What is being printed:
At 1.5s:
```
New file discovered: /tmp/scalaz-stream-test7760941790262648503/testFile-0
resetting
```
At 3s (after the `newFiles` process had been killed already at 2s):
```
Releasing WatchService
resetting
Releasing WatchService
DONE
```

Now my question is, why is the `WatchService` resource being released twice?

Given the logic described in the wiki, I'd expect to see only this at the end:
```
Releasing WatchService
resetting
DONE
```

**Comment by djspiewak** [comment] 2015-03-30 21:30
```scala
} onComplete reset append repeatedStep(ws)
```

This looks a bit suspicious to me.  You're resetting between each step of the recursion?  (note that this is *inside* of the `await`, which is thus inside of `repeatedStep`)  This could very directly lead to multiple resets if you run one step successfully then get interrupted during the *next* step.  Basically, you would be getting multiple resets precisely because you're defining multiple finalizers!

I haven't completely grokked the example yet, so I could be chasing a red herring, but I'd like to understand that particular construction.

**Comment by dansanduleac** [comment] 2015-03-31 11:17
Yup, that's how the javadoc says to use it - I'm resetting after each `take`, because every time I get a `WatchKey` out of `take`, it's going to be in the "signalled" state, and in order for it to receive more events, I need to place it back into the "ready" state by calling `reset`.

> When an event for an object is detected the key is signalled, and if not currently signalled, it is queued to the watch service so that it can be retrieved by consumers that invoke the `poll` or `take` methods to retrieve keys and process events. Once the events have been processed the consumer invokes the key's `reset` method to reset the key which allows the key to be signalled and re-queued with further events.

I'm not sure I follow what you mean in this case by "this could very directly lead to multiple resets". I'm not getting multiple resets - rather, the finalizer one step _outside_ the bit which calls `reset` is getting called twice.
The reset after "newPaths process has finished" is expected, as there is a new event (take returned something), so there should be a reset for it - I just don't process the new event because the `newPaths` process had been killed already at that point.

**Comment by djspiewak** [comment] 2015-03-31 15:38
> Yup, that's how the javadoc says to use it - I'm resetting after each take, because every time I get a WatchKey out of take, it's going to be in the "signalled" state, and in order for it to receive more events, I need to place it back into the "ready" state by calling reset.

Then I think the best thing to do would be to move the `append` outside of the `await`.  This will make the semantics a lot clearer.  Remember that finalizers sort of barely almost don't work in the presence of `append`, and having an infinite sequence of *nested* `await`s is a concept that makes my head spin.  The other nice thing is that by moving `append` outside of `await`, you can actually just get rid of the explicit recursion and use the `repeat` combinator instead.

> I'm not getting multiple resets - rather, the finalizer one step outside the bit which calls reset is getting called twice.

Like I said, I still haven't fully grokked the example yet.  :-)  The multiple invocations of `release` seems straight-up buggy.  I'm rather unsure where it could be coming from…

**Comment by djspiewak** [comment] 2015-04-01 18:01
@dansanduleac Some ideas ruminating around on this…  If you move the `append` outside of the `await`, do you still see the double `release`?  If not, then I think we may have a bug with finalizers on deeply nested awaits.  Should be easy enough to reproduce if that's the case…

As a follow up question, is the double `release` deterministic?  Or do you sometimes not see it?

**Comment by dansanduleac** [comment] 2015-04-03 17:45
@djspiewak Yes I do, unfortunately :( Moving `append repeatedStep(ws)` after the await (the equivalent of doing `.repeat` on the whole thing) changes nothing in this particular case.
Actually I don't really see a difference between the two, the reason I put it on the inside was because that's what `Process.repeatEval` was doing.

Btw - I still see the same behaviour even if I change the `.onComplete(reset)` to a plain `append reset` (in which case the 2nd `reset` isn't called, as expected, but "newPaths process has finished" still gets printed twice).

**Comment by djspiewak** [comment] 2015-04-03 23:16
@dansanduleac Ok, something is just broken then.  The fact that it's deterministic is really good, actually, since it makes it easier to test.  I'll see what I can come up with…

**Comment by djspiewak** [comment] 2015-04-07 20:32
@dansanduleac So I'm having a really hard time getting your example even running.  The example as written does not compile, and modifying it to compile produces an example which does not run (it hangs in some file system stuff).  Could you help me by reducing this just a bit to something that is self-contained?  I don't mind if it still uses the NIO filesystem things, so long as it is self-contained, compiling and running.

**Comment by edwinchoi** [comment] 2015-04-10 01:26
@djspiewak in the PR for the runAsync work, you mentioned that `cont` finalizers may be invoked multiple times when the task is running.. Isn't the "release" here reachable from cont? Seems to be the case, and assuming `WatchService.take` is not preempted by `close`, the second `dropFile` would case take to unblock, which would cause the finalizers to be called again.

I really wish the assumption that a task may never complete was not applied everywhere.. This is one of the reasons I dislike using Akka actors for local JVM stuff (delivery not guaranteed), but it seems the same weak guarantees are here as well.
I would find it immensely useful if there were a way to separate executions that may never complete vs. ones that will always complete (aka transactions). Comparing to RxJava, scalaz-stream is much easier to use and extend, but the haphazard preemption makes it more difficult to write safe code when runAsync is in the picture.
The issue isn't simply that exactly once semantics are being violated, it's that the out of order completions can result in some bugs that are very difficult to track down. For example, if the outer await acquires a JDBC connection and the inner await applies a transaction atomically, closing the connection on completion.. if the process is interrupted while the transaction is running, and the connection is closed, the partial changes will be automatically committed.

Anyway, I'll stop hijacking this thread and start a separate disucssion with my thoughts on the matter when I can find some free time :).

**Comment by edwinchoi** [comment] 2015-04-10 01:29
(Forgive me if my post jumps around a lot.. Writing on a tiny screen where I can only see a few lines at a time)

**Comment by dansanduleac** [comment] 2015-04-10 09:03
@djspiewak Oops really sorry - I've fixed the example, it's now guaranteed to compile. 
How do you mean self-contained? It's not accessing any external stuff, as it's creating its own temp directory and only operating inside it.

**Comment by djspiewak** [comment] 2015-04-10 19:59
@dansanduleac By "self-contained" I mean, I want to be able to copy/paste the example into a test, convert the printlns into assertions and be able to see the bug manifesting.  Even if it isn't manifesting deterministically (that's what loops are for).  Eventually I'll golf out the temp directory stuff, but that aspect of things is fine for now.

The revised example in the OP looks like it might be what I'm looking for.  I'll give it a shot today or tomorrow and let you know.

**Comment by djspiewak** [comment] 2015-04-11 18:53
@dansanduleac Tried this again, and I basically hit the same thing I hit last time.  Here is the line that is giving me trouble:

```scala
time.sleep(1500.milliseconds) ++ (Process eval_ Task.delay { Files.createFile(f) })
```

This compiles, but it hangs at runtime.  Stack trace:

```
   java.lang.Thread.State: RUNNABLE
	at scalaz.stream.ProcessSpec$$anonfun$1$$anonfun$7.apply(ProcessSpec.scala:387)
	at scalaz.stream.ProcessSpec$$anonfun$1$$anonfun$7.apply(ProcessSpec.scala:385)
	at scalaz.stream.Process$$anonfun$flatMap$1.apply(Process.scala:42)
	at scalaz.stream.Process$$anonfun$flatMap$1.apply(Process.scala:42)
	at scalaz.stream.Util$.Try(Util.scala:38)
	at scalaz.stream.Process$class.flatMap(Process.scala:42)
	at scalaz.stream.Process$Emit.flatMap(Process.scala:573)
	at scalaz.stream.Process$$anonfun$flatMap$4.apply(Process.scala:44)
	at scalaz.stream.Process$$anonfun$flatMap$4.apply(Process.scala:44)
	at scalaz.stream.Process$Append.extend(Process.scala:624)
	at scalaz.stream.Process$class.flatMap(Process.scala:44)
	at scalaz.stream.Process$Append.flatMap(Process.scala:613)
	at scalaz.stream.Process$$anonfun$flatMap$4.apply(Process.scala:44)
	at scalaz.stream.Process$$anonfun$flatMap$4.apply(Process.scala:44)
	at scalaz.Free$$anonfun$map$1.apply(Free.scala:64)
	at scalaz.Free$$anonfun$map$1.apply(Free.scala:64)
	at scalaz.Free.resume(Free.scala:81)
	at scalaz.Free.go2$1(Free.scala:116)
	at scalaz.Free.go(Free.scala:120)
	at scalaz.Free.run(Free.scala:174)
	at scalaz.stream.Process$$anonfun$go$1$1.apply(Process.scala:80)
	at scalaz.stream.Process$$anonfun$go$1$1.apply(Process.scala:80)
	at scalaz.stream.Util$.Try(Util.scala:38)
	at scalaz.stream.Process$class.go$1(Process.scala:80)
	at scalaz.stream.Process$class.step(Process.scala:93)
	at scalaz.stream.Process$Append.step(Process.scala:613)
	at scalaz.stream.Process$SourceSyntax$$anonfun$11$$anonfun$scalaz$stream$Process$SourceSyntax$$anonfun$$go$9$1.apply(Process.scala:1163)
	at scalaz.stream.Process$SourceSyntax$$anonfun$11$$anonfun$scalaz$stream$Process$SourceSyntax$$anonfun$$go$9$1.apply(Process.scala:1163)
	at scalaz.concurrent.Task$$anonfun$delay$1.apply(Task.scala:201)
	at scalaz.concurrent.Task$$anonfun$delay$1.apply(Task.scala:201)
	at scalaz.concurrent.Task$$anonfun$suspend$1$$anonfun$3.apply(Task.scala:209)
	at scalaz.concurrent.Task$$anonfun$suspend$1$$anonfun$3.apply(Task.scala:209)
	at scalaz.concurrent.Task$.Try(Task.scala:295)
	at scalaz.concurrent.Task$$anonfun$suspend$1.apply(Task.scala:209)
	at scalaz.concurrent.Task$$anonfun$suspend$1.apply(Task.scala:209)
	at scalaz.concurrent.Future$class.step(Future.scala:112)
	at scalaz.concurrent.Future$BindSuspend.step(Future.scala:200)
	at scalaz.concurrent.Future$class.listen(Future.scala:77)
	at scalaz.concurrent.Future$BindSuspend.listen(Future.scala:200)
	at scalaz.concurrent.Future$class.runAsync(Future.scala:144)
	at scalaz.concurrent.Future$BindSuspend.runAsync(Future.scala:200)
	at scalaz.concurrent.Future$class.run(Future.scala:161)
	at scalaz.concurrent.Future$BindSuspend.run(Future.scala:200)
	at scalaz.concurrent.Task.run(Task.scala:96)
	at scalaz.stream.Process$SourceSyntax.stepAsync(Process.scala:1335)
	at scalaz.stream.wye$$anonfun$apply$43.scalaz$stream$wye$$anonfun$$runSide$1(wye.scala:660)
	at scalaz.stream.wye$$anonfun$apply$43$$anonfun$3.apply(wye.scala:663)
	at scalaz.stream.wye$$anonfun$apply$43$$anonfun$3.apply(wye.scala:663)
	at scalaz.stream.wye$$anonfun$apply$43.go$7(wye.scala:778)
	at scalaz.stream.wye$$anonfun$apply$43.scalaz$stream$wye$$anonfun$$runY$1(wye.scala:790)
	at scalaz.stream.wye$$anonfun$apply$43$$anonfun$apply$44.apply(wye.scala:810)
	at scalaz.stream.wye$$anonfun$apply$43$$anonfun$apply$44.apply(wye.scala:794)
	at scalaz.concurrent.Actor.scalaz$concurrent$Actor$$act(Actor.scala:44)
	at scalaz.concurrent.Actor$$anonfun$schedule$1.apply$mcV$sp(Actor.scala:40)
	at scalaz.concurrent.Actor$$anonfun$schedule$1.apply(Actor.scala:40)
	at scalaz.concurrent.Actor$$anonfun$schedule$1.apply(Actor.scala:40)
	at scalaz.concurrent.StrategysLow$$anon$3$$anon$4.call(Strategy.scala:65)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

I have no idea *why* things would be stuck in that fashion, because it's not stuck in `Files` but rather in the process/task composition!  Very weird, but also very consistent.

**Comment by pchlupacek** [comment] 2015-04-12 06:31
@djspiewak have you tried to run this while converting the `object` spec just to `class`?  Usually sort of these deadlocks just helps me when I either make the processes strict or just convert object -> class, thus avoiding the object initialization, that causes quite often deadlock.

**Comment by dansanduleac** [comment] 2015-04-12 13:16
That's really surprising. I should mention I'm using 0.7a, scala 2.11.6 and
java 1.8.0_31 on linux, maybe it's a setup thing.

**Comment by edwinchoi** [comment] 2015-04-12 17:05
@djspiewak try using a custom strategy with a cached thread pool

**Comment by djspiewak** [comment] 2015-04-12 17:06
@edwinchoi `cont` finalizers *should not be* invoked multiple times unless the finalizer is placed within both the `End` and the non-`End` branches of the `awaitOr`.  Coming back to our illustration:

```scala
await(t) { _ => p1 onComplete f1 } onComplete f2
```

In the above, `f1` and `f2` are guaranteed to be invoked at most once, where `f1` is guaranteed to be invoked iff `t` completes (regardless of interrupt) and `f2` is guaranteed to run.  This comes with the caveat that, if you hide this `await` on the right side of an `append` (or equivalently inside of a `flatMap`), you lose these guarantees from a strict lexical standpoint and contend with the weaker caveat of "if the `await` process is run".

The interesting thing is that `f2` is by far the simplest finalizer juggling that `stepAsync` does.  All the weird properties are surrounding `f1`, and yet `f2` is the finalizer in question in this bug report.

@pchlupacek Swapping to a class worked.  That makes really no sense at all.  *sigh*

**Comment by djspiewak** [comment] 2015-04-12 17:09
@dansanduleac Ok, I've got the test running and failing locally.  Off to the races!

**Comment by pchlupacek** [comment] 2015-04-12 17:32
@djspiewak this issue with Specs being objects is killing me always. I think we shall move all our specs to be classes (any volunteers to do that? :-) ). This issue comes with scala's object initialization deadlock which is completely insane, and I think there must be just a bug in compiler that if two threads compete for object instance during its creating only one gets notified, whilst the other just awaits notify. Its just my guess.  

I will actually open issue to track this separately.

**Comment by djspiewak** [comment] 2015-04-12 17:33
Have a minimized test case:

```scala
  property("stepAsync invokes outer finalizer exactly once on observed process") = secure {
    val releaseCount = new AtomicInteger

    val release = new SyncVar[Unit]
    val release2 = new SyncVar[Unit]

    val results = new SyncVar[Cause \/ (Seq[Unit], Process.Cont[Task, Unit])]

    def observer(u: Unit): Task[Unit] = Task now u

    val p = await(Task delay { release.put(()); release2.get }) { _ =>
      halt
    } onComplete eval_(Task delay { releaseCount.incrementAndGet() }) observe (sink lift observer)

    val interrupt = p stepAsync results.put

    release.get
    interrupt(Kill)
    release2.put(())

    results.get(3000).isDefined :| "process completed" &&
      (releaseCount.get() == 1) :| s"releaseCount.get() == ${releaseCount.get()}"
  }
```

The problem is in the `observe`.  If I remove that clause, the test passes.

**Comment by pchlupacek** [comment] 2015-04-12 17:42
@djspiewak I think problem perhaps may be in tee. If you recall what we have been discussing about "swaping" finalizers of await from outer to inner part, I think we may be actually hitting this. Look on tee, https://github.com/scalaz/scalaz-stream/blob/master/src/main/scala/scalaz/stream/Process.scala#L180 and L190, as well. you see that that contL is actually positioned from outside of the await to be inside the await in rcv?

**Comment by djspiewak** [comment] 2015-04-12 17:44
@pchlupacek 

Crumbs…

```scala
  property("stepAsync invokes outer finalizer exactly once on observed process") = secure {
    val releaseCount = new AtomicInteger

    val release = new SyncVar[Unit]
    val release2 = new SyncVar[Unit]

    val results = new SyncVar[Cause \/ (Seq[Unit], Process.Cont[Task, Unit])]

    val p = await(Task delay { release.put(()); release2.get }) { _ =>
      halt
    } onComplete eval_(Task delay { releaseCount.incrementAndGet() }) pipe await1

    val interrupt = p stepAsync results.put

    release.get
    interrupt(Kill)
    release2.put(())

    results.get(3000).isDefined :| "process completed" &&
      (releaseCount.get() == 1) :| s"releaseCount.get() == ${releaseCount.get()}"
  }
```

You're absolutely right.

**Comment by pchlupacek** [comment] 2015-04-12 21:11
@djspiewak ok lets take this as priority. I think this is in fact related to #333. I think we shall follow in #333 and leave this open?

**Comment by djspiewak** [comment] 2015-04-13 02:50
@pchlupacek It's possible that it's related to #333.  The fact that the algebra is problematic certainly affects many issues.  I'm still looking into it, since intuitively it seems to me that the lifting in `pipe` (and `tee` and `wye`) should be sound relative to our new finalizer semantics.  I'd like to leave both issues open at present while we track things down more precisely.

**Comment by djspiewak** [comment] 2015-04-13 23:58
For anyone who is having this issue and needs to get around it *now*, **there is a workaround**: use `wye` instead of `tee` or `pipe`.  You will need to specialize the effect on `Task` (since `wye` doesn't work otherwise), and you may need to port a `Process1` or `Tee` to `Wye` (trivial), but it will get around the multiply-run finalizer issue.  The cost of doing this, of course, is some performance, less abstraction (specialized on `Task`) and concurrency where perhaps you didn't want it.

**Closed** 2015-05-16 06:02 UTC
Labels: bug
