### ISSUE TITLE
Backport fixes for 0.7.1

### ISSUE THREAD

**Issue by djspiewak** [scalaz/scalaz-stream#394] opened 2015-05-26 21:34 UTC
Please comment on the list below.  Also, we need to identify all of the commits associated with these semantic changes so that we can cherry pick.

- `njoin` deadlock (76155a3)
- Queue data loss on dequeue error (656f8d8..4b3dcae)
- `signalUnset` (e9ea673)
- Signal initial value state (2b47e61)

Feel free to suggest more candidates.

**Comment by psnively** [comment] 2015-05-27 18:32
Wow.

Well, hmm. I'm trying to figure out what to say about this that doesn't boil down to "I categorically refuse to use git anymore. Get back to me when you've switched to darcs."

I've created a branch and tried cherry-picking the above. Only the first one cherry-picks cleanly. The others are piles of conflicts that need resolving when I'm relatively unfamiliar with the codebase, and even when I do manage to resolve them in what seem like sensible ways, sure enough, compiling fails because git isn't smart enough to automatically bring along dependent patches. I've found several articles on how to go through the process of finding cherry-picking dependencies, ranging from "you have _got_ to be kidding me" to "NFW."

So I guess I could really use a couple of things: first and foremost, talking in off the ledge (why do we tolerate this level of middle-finger-extending from such an important tool, emphasis on "tool?"), secondarily any pointers to the most sane "yeah, this sucks; here's the best step-by-step on tracking down cherry-picking dependencies I know of" sort of thing, and finally, maybe a bit of a hint as to what some of the other commits are likely to be from someone more familiar with the code.

Beyond that, I really am tempted to put up a fork of this on, e.g. [hub.darcs.net](http://hub.darcs.net/), because this really is mashing my "run, don't walk, away" buttons.

**Comment by djspiewak** [comment] 2015-05-27 19:08
@psnively The conflicts on the first two changes are trivial and don't really require any knowledge of the codebase (the compiler guides you on the two which are slightly less apparent, which is good because I got one of them wrong).  The third change required an additional commit (which I have added to the OP), so it's definitely in the weirder semantic knowledge camp.

Cherry picking isn't an area where Git has the greatest tooling (notably, you can't cherry-pick a range), but it's also not an encouraged operation so I don't thing it's that big of a deal.  I would recommend configuring `mergetool`, since it makes these sorts of things dramatically easier.

Not trying to turn this into a "darcs vs git" discussion, but honestly darcs is not a panacea.  It has a better changeset algebra, granted, but conflicts are *inherent* to a system which represents artifacts with higher semantic meaning as simple ASCII.  For many of the changes involved here, Darcs simply would not have done any better than Git did.

---

As a bit of learning, here is what I did in order.  First, note that I arranged the `ul` in the OP in order of dependency, so I knew a priori that I needed to cherry-pick things from top to bottom.  Second, I have the following `git config` option:

```
$ git config merge.tool
opendiff
```

I recommend the same.  You lose syntax highlighting on diffs, but you acquire a dramatically more streamlined process for resolving merge conflicts.  Be sure to expand the third (lower) pane, which is mysteriously collapsed by default.

```
$ git branch feature/0.7.1 release/0.7a
$ git checkout feature/0.7.1
$ git cherry-pick 76155a3
```

This one applies cleanly, as one would expect.

```
$ git log 656f8d8..4b3dcae
```

This one is tedious, because we need to cherry-pick each commit in turn and there may be conflicts along the way.  The end-result was the following:

```
$ git cherry-pick ccc204da093df5243547fdf2683c0a7d108a0e67
$ git mergetool
# resolve conflicts here (these are trivial)
$ git commit
$ git cherry-pick 4a093d9ab0c6e6836bae9d3acf4efecae85f12d1
$ git cherry-pick 6450f229bee86863ddeecfbff3a6b50269bcc5d2
$ git cherry-pick 373f11555a22a1acb262aa6070014583fb9bcf44
$ git cherry-pick 4b3dcae7b4616cab864632dc068bc3fb556d14f1
$ git mergetool
# slightly less-trivial conflicts; required a minor change afterward to make the compiler happy
$ git commit
```

Now we're on to the `Signal` fixes:

```
$ git cherry-pick e9ea673
$ git mergetool
# trivial stuff; mostly documentation conflicts
$ git commit
$ git cherry-pick 2b47e61
$ git mergetool
# trivial
$ git commit
```

After that, I needed to apply the following diff to compensate for an import that I missed in the last `mergetool` usage:

```diff
diff --git a/src/test/scala/scalaz/stream/AsyncSignalSpec.scala b/src/test/scala/scalaz/stream/AsyncSignalSpec.scala
index 13ba4f6..092064e 100644
--- a/src/test/scala/scalaz/stream/AsyncSignalSpec.scala
+++ b/src/test/scala/scalaz/stream/AsyncSignalSpec.scala
@@ -12,6 +12,7 @@ import scalaz.syntax.monad._
 import scalaz.{-\/, Nondeterminism, \/, \/-}
 
 object AsyncSignalSpec extends Properties("async.signal") {
+  import Process._
 
   implicit val scheduler = DefaultScheduler
 ```

Pretty straightforward; again the compiler guided me (it complained about not having `eval_` in scope).

I ran `> compile` and `> test` a few times during this process, just as a sanity check.  The only semantic error I ran into was at the end, which I fixed with the above diff.  Judging by the timestamp on your comment, the whole process (including identifying the fourth change that was missing in the OP) took me less than 20 minutes.

You can find all of this in [djspiewak:feature/0.7.1](https://github.com/djspiewak/scalaz-stream/tree/feature/0.7.1).

---

To be clear, my intention really isn't to sound condescending here, so I apologize if the above comes off that way.  I'm mostly reacting to the anti-Git rant, which seems a bit unjustified.  There are plenty of things that I don't like about Git, or that I think it could do better (such as having a stateful process for cherry-picking a range, similar to rebase), but this particular transformation was not an area where Darcs would have been a dramatic upgrade.

**Comment by psnively** [comment] 2015-05-27 19:32
Thanks, Daniel.

Of course you're right, and maybe there are some process-related lessons to be found here as well, so that we don't find ourselves in the git cherry-pick edge-case when things like trying to move the release cycle ball forward without taking branches that aren't yet blessed wholesale do come up. Regardless, I did blow off some steam, so I do apologize for that.

Back to trying to be constructive: I personally prefer Perforce's P4Merge to opendiff. There's a pretty good [post](https://gist.github.com/tony4d/3454372) about setting it up, FWIW.

Thanks again!

**Comment by djspiewak** [comment] 2015-05-27 20:17
@psnively I do like 4 pane merge tools (like p4merge) as a concept.  I think the problem I've always had with them is the fact that they tend to be much more complicated to navigate via the keyboard.  One thing that opendiff does *extremely* well is rapidly paging through conflicts and resolution selecting solely using the keyboard.  Where it gets a little clumsy is moving around and editing the merge results explicitly.  It's still very doable (contrary to most posts about it, it's a 3 pane tool, not 2 pane), but it's a little clunkier than I would like.

In any case, we have our release branch.  Could you take a look at the results and see if it does in fact meet your needs?  Obviously it would be better not to push an 0.7.1 hastily before we actually have what we want.  :-)

**Comment by djspiewak** [comment] 2015-05-28 18:29
@psnively @runarorama Can you confirm whether or not the list of changes in the OP satisfies your needs for an 0.7.1a release?

**Comment by dcsobral** [comment] 2015-05-28 19:30
Cherry-picking a range is done with something that is not cherry-pick: git
format-patch (https://git-scm.com/docs/git-format-patch). That doesn't
directly copy stuff: it produces a file that contains changes and commit
logs, which is then applied with git am. Excellent tool when you want to
move commits between completely separate repositories.

Inside the same repository, rebase could be used as well for a range
(that's what cherry-pick does behind the scene), but it's parameters are
arcane, so format-patch might well be easier.

On 27 May 2015 at 13:08, Daniel Spiewak <notifications@github.com> wrote:

> @psnively <https://github.com/psnively> The conflicts on the first two
> changes are trivial and don't really require any knowledge of the codebase
> (the compiler guides you on the two which are slightly less apparent, which
> is good because I got one of them wrong). The third change required an
> additional commit (which I have added to the OP), so it's definitely in the
> weirder semantic knowledge camp.
>
> Cherry picking isn't an area where Git has the greatest tooling (notably,
> you can't cherry-pick a range), but it's also not an encouraged operation
> so I don't thing it's that big of a deal. I would recommend configuring
> mergetool, since it makes these sorts of things dramatically easier.
>
> Not trying to turn this into a "darcs vs git" discussion, but honestly
> darcs is not a panacea. It has a better changeset algebra, granted, but
> conflicts are *inherent* to a system which represents artifacts with
> higher semantic meaning as simple ASCII. For many of the changes involved
> here, Darcs simply would not have done any better than Git did.
> ------------------------------
>
> As a bit of learning, here is what I did in order. First, note that I
> arranged the ul in the OP in order of dependency, so I knew a priori that
> I needed to cherry-pick things from top to bottom. Second, I have the
> following git config option:
>
> $ git config merge.tool
> opendiff
>
> I recommend the same. You lose syntax highlighting on diffs, but you
> acquire a dramatically more streamlined process for resolving merge
> conflicts. Be sure to expand the third (lower) pane, which is mysteriously
> collapsed by default.
>
> $ git branch feature/0.7.1 release/0.7a
> $ git checkout feature/0.7.1
> $ git cherry-pick 76155a3
>
> This one applies cleanly, as one would expect.
>
> $ git log 656f8d8..4b3dcae
>
> This one is tedious, because we need to cherry-pick each commit in turn
> and there may be conflicts along the way. The end-result was the following:
>
> $ git cherry-pick ccc204da093df5243547fdf2683c0a7d108a0e67
> $ git mergetool
> # resolve conflicts here (these are trivial)
> $ git commit
> $ git cherry-pick 4a093d9ab0c6e6836bae9d3acf4efecae85f12d1
> $ git cherry-pick 6450f229bee86863ddeecfbff3a6b50269bcc5d2
> $ git cherry-pick 373f11555a22a1acb262aa6070014583fb9bcf44
> $ git cherry-pick 4b3dcae7b4616cab864632dc068bc3fb556d14f1
> $ git mergetool
> # slightly less-trivial conflicts; required a minor change afterward to make the compiler happy
> $ git commit
>
> Now we're on to the Signal fixes:
>
> $ git cherry-pick e9ea673
> $ git mergetool
> # trivial stuff; mostly documentation conflicts
> $ git commit
> $ git cherry-pick 2b47e61
> $ git mergetool
> # trivial
> $ git commit
>
> After that, I needed to apply the following diff to compensate for an
> import that I missed in the last mergetool usage:
>
> diff --git a/src/test/scala/scalaz/stream/AsyncSignalSpec.scala b/src/test/scala/scalaz/stream/AsyncSignalSpec.scala
> index 13ba4f6..092064e 100644--- a/src/test/scala/scalaz/stream/AsyncSignalSpec.scala+++ b/src/test/scala/scalaz/stream/AsyncSignalSpec.scala@@ -12,6 +12,7 @@ import scalaz.syntax.monad._
>  import scalaz.{-\/, Nondeterminism, \/, \/-}
>
>  object AsyncSignalSpec extends Properties("async.signal") {+  import Process._
>
>    implicit val scheduler = DefaultScheduler
>
> Pretty straightforward; again the compiler guided me (it complained about
> not having eval_ in scope).
>
> I ran > compile and > test a few times during this process, just as a
> sanity check. The only semantic error I ran into was at the end, which I
> fixed with the above diff. Judging by the timestamp on your comment, the
> whole process (including identifying the fourth change that was missing in
> the OP) took me less than 20 minutes.
>
> You can find all of this in djspiewak:feature/0.7.1
> <https://github.com/djspiewak/scalaz-stream/tree/feature/0.7.1>.
> ------------------------------
>
> To be clear, my intention really isn't to sound condescending here, so I
> apologize if the above comes off that way. I'm mostly reacting to the
> anti-Git rant, which seems a bit unjustified. There are plenty of things
> that I don't like about Git, or that I think it could do better (such as
> having a stateful process for cherry-picking a range, similar to rebase),
> but this particular transformation was not an area where Darcs would have
> been a dramatic upgrade.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scalaz/scalaz-stream/issues/394#issuecomment-106038388>
> .
>



-- 
Daniel C. Sobral

I travel to the future all the time.

**Comment by djspiewak** [comment] 2015-05-28 20:10
@dcsobral `format-patch` discards commit metadata and is thus inappropriate for the backporting we wanted to do here.

**Comment by psnively** [comment] 2015-05-28 20:17
Unfortunately, it doesn't. @runarorama and I are digging further. Thanks!

**Comment by runarorama** [comment] 2015-05-29 00:40
It does look like the immediate problem is fixed (a signalOf compareAndSet
not giving a value), but this has unveiled another issue underneath. I
strongly suspect that the underlying issue is our fault though. Will report
back when we have isolated the problem.

Rúnar

**Comment by dcsobral** [comment] 2015-05-29 02:24
What metadata does it discard that is not discarded by cherry-pick?

On 28 May 2015 at 14:10, Daniel Spiewak <notifications@github.com> wrote:

> @dcsobral <https://github.com/dcsobral> format-patch discards commit
> metadata and is thus inappropriate for the backporting we wanted to do here.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scalaz/scalaz-stream/issues/394#issuecomment-106583002>
> .
>



-- 
Daniel C. Sobral

I travel to the future all the time.

**Comment by djspiewak** [comment] 2015-05-29 17:02
@dcsobral I was under the impression that `format-patch` both squashed and dropped commit message and authorship information.  That appears to be incorrect, though it does have a different semantic with respect to the patch applier than `cherry-pick` does.

**Comment by psnively** [comment] 2015-05-29 18:08
FYI, I’ve cherry-picked ranges successfully using git 2.4.1. :-)

**Comment by djspiewak** [comment] 2015-05-29 18:08
@psnively I'm pretty sure the problem with cherry picking this particular range is the fact that there was a merge conflict.  Unlike rebase, which has a stateful process to incrementally resolve conflicts, cherry-pick just fails on the first merge conflict, forcing you to do the range iteration by hand.

**Comment by djspiewak** [comment] 2015-06-01 16:13
@pchiusano I verified with @runarorama that Verizon is good to go with the 0.7.1 defined by my branch (djspiewak:feature/0.7.1).  I can confirm that RichRelevance is as well.  We're using some of the fixes in master that didn't make the 0.7.1 cut, but we can do without those changes if it means no longer maintaining snapshots of the entire scalaz-stream ecosystem.

So in short: ready for 0.7.1 release!

**Comment by pchiusano** [comment] 2015-06-02 14:20
Okay, cool. Have we confirmed (or are we reasonably certain) that this is
binary compatible with 0.7?

If so, can you merge to series/0.7 and create a tag release/0.7.1? I'll
then do the release.

**Comment by djspiewak** [comment] 2015-06-02 20:25
@pchiusano Source compatible, yes absolutely (as long as people aren't using internal APIs, specifically `Signal.apply`).  Unfortunately, binary compatibility is something we missed.  This is lost due to the parameter I added to `async.boundedQueue`.  The parameter has a default value, which makes us source compatible (as long as you're not using `boundedQueue` as a HoF), but unfortunately it isn't binary compatible.

We can make it binary compatible though by changing the default parameter encoding to use a straight-up overload.  That would similarly break HoF usage of `boundedQueue`, but it would be binary compatible.  WDYT?

**Comment by pchiusano** [comment] 2015-06-03 03:44
Yeah, I'd really like it to be binary compatible (this goes for anything in
0.7.x). I explicitly wanted to avoid doing two binary breaking releases
within a few months of each other.

**Comment by djspiewak** [comment] 2015-06-03 16:58
@pchiusano Ok, I'll replace the default param with an overload on this branch (it'll remain a default param for 0.8, since we don't mind breaking compatibility there).  That should be done a little later today.

**Comment by djspiewak** [comment] 2015-06-03 19:27
@pchiusano Ok, we're tagged and ready to go.

**Comment by pchiusano** [comment] 2015-06-03 19:34
Building now...

**Comment by pchiusano** [comment] 2015-06-03 19:45
All right, there are 0.7.1 and 0.7.1a published against 2.10.5 and 2.11.6. Could someone take the lead on putting some release notes on the wiki? I can send out a quick release announcement that links to them. In any case, @psnively and @runarorama you should be able to access the published jars now, from the same place, just use "0.7.1a" instead of "0.7a" (or 0.7.1 if you are still on scalaz 7.0.x)

**Comment by djspiewak** [comment] 2015-06-03 21:15
@pchiusano Release notes [here](https://github.com/scalaz/scalaz-stream/wiki/0.7.1).

**Comment by pchiusano** [comment] 2015-06-03 21:50
Announced! https://groups.google.com/forum/#!topic/scalaz/bygJQV1VQ-g Closing this issue.

**Closed by pchiusano** 2015-06-03 21:50 UTC
Labels: release
